//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeojectTWI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInventoryData()
        {
            this.tblInventoryHistories = new HashSet<tblInventoryHistory>();
            this.tblMasterWarrenties = new HashSet<tblMasterWarrenty>();
            this.tblTickets = new HashSet<tblTicket>();
        }
    
        public int InventoryID { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> ToTheStore { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<bool> ToTheOutside { get; set; }
        public Nullable<System.DateTime> OutedDateFromStore { get; set; }
    
        public virtual tblMasterStore tblMasterStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryHistory> tblInventoryHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMasterWarrenty> tblMasterWarrenties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicket> tblTickets { get; set; }
    }
}
