//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeojectTWI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMasterStore()
        {
            this.tblInventoryDatas = new HashSet<tblInventoryData>();
        }
    
        public int mStoreId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> perchesedCount { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<System.DateTime> PerchesedDate { get; set; }
        public Nullable<int> RecoredEnterdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryData> tblInventoryDatas { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
    }
}
