//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeojectTWI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportType
    {
        public int ReportTypeID { get; set; }
        public Nullable<int> ReportCategoryId { get; set; }
        public Nullable<int> ReportTypeValue { get; set; }
        public string ReportTypeName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tblReportCategory tblReportCategory { get; set; }
    }
}
