//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeojectTWI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarrentyExtendedDate
    {
        public int weId { get; set; }
        public Nullable<int> mWarrentyId { get; set; }
        public Nullable<System.DateTime> expiredDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> IsWarrentyExtended { get; set; }
        public Nullable<System.DateTime> warrentyExtendedFromDate { get; set; }
        public Nullable<System.DateTime> warrentyExtendedToDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    
        public virtual tblMasterWarrenty tblMasterWarrenty { get; set; }
    }
}
