//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeojectTWI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarrentyhistory
    {
        public int whId { get; set; }
        public Nullable<int> mWarrentyId { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual tblMasterWarrenty tblMasterWarrenty { get; set; }
    }
}
